bot:
  token: "'MTI3NzQ0MzczODMxNDA4NDQ1Ng.G8ieaI.VevEyQ-5HGeSIsPCOhmVzotnCXe_i5dqPKMmPo'"  # Токен для аутентификации бота
  prefix: "!"              # Префикс для текстовых команд (если используются)

server:
  guild_id: 1160613896286130287  # ID сервера Discord
  adept_role_id: 1274711574229291089
  vip_role_id: 0
  mvp_role_id: 0
  apex_role_ip: 0
